# /game/BUILD

cc_binary(
    name = "game",
    srcs = ["main.cc"],
    visibility = ["//visibility:public"],
    deps = [
        "//player",
        "//renderer",
        "//utils",
        "@ncurses//:main",
    ],
)
