cc_binary(
    name = "hello_world",
    srcs = [
        "hello_world.cc",
    ],
    deps = ["@abseil-cpp//absl/strings"],
)

cc_binary(
    name = "culprit_set",
    srcs = [
        "culprit_set.cc",
    ],
)
