cc_binary(
    name = "culprit_set",
    srcs = [
        "culprit_set.cc",
        "culprit_set.h",
    ],
    deps = [
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/container:flat_hash_set",
    ],
)
